# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Site name
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude: [Gemfile, Gemfile.lock, vendor, README.md]

# TODO: Enable once the site has gone live
# google_analytics:
#   tracking_code: UA-660910-14

# everypolitician:
#   sources:
#     assembly: https://github.com/everypolitician/everypolitician-data/raw/master/data/Nigeria/Assembly/ep-popolo-v1.0.json
#     senate: https://github.com/everypolitician/everypolitician-data/raw/nigeria-senate/data/Nigeria/Senate/ep-popolo-v1.0.json

collections:
  # Assembly
  assembly_people:
    output: true
    permalink: '/assembly/person/:path/'
  assembly_organizations:
    output: true
    permalink: '/assembly/organisation/:path/'
  assembly_areas:
    output: true
    permalink: '/assembly/place/:path/'

  # Senate
  senate_people:
    output: true
    permalink: '/senate/person/:path/'
  senate_organizations:
    output: true
    permalink: '/senate/organisation/:path/'
  senate_areas:
    output: true
    permalink: '/senate/place/:path/'

  executive_governors:
    output: true
    permalink: '/governors/person/:path/'
